name: container
on: push

jobs:
   node-docker:
      runs-on: ubuntu-latest
      container: 
         image: node:14-alpine3.13
      steps:
         - name: Log node version
           run: |
              node node-version:
              cat /etc/